In [6]:
# Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:

import numpy as np

# a) Addition of 2 in all the element


array = np.array([6, 10, 14, 16, 20])
print("After Adding 2 : ",array+2)

# b) Multiply 3 with all the elements


print("After Multiplying by 3 : ",array*3)

# c) Divide every element by 2


print("After Dividing by 2 : ",array/2)

After Adding 2 :  [ 8 12 16 18 22]
After Multiplying by 3 :  [18 30 42 48 60]
After Dividing by 2 :  [ 3.  5.  7.  8. 10.]


In [2]:
# Q2 Questions on Basic NumPy Array:

# a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

arr = np.array([1,2,3,6,4,5])
arr[::-1]

# b) Find the most frequent value and their indice(s) in the following arrays: i. x = np.array([1,2,3,4,5,1,2,1,1,1]) ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

# i. x = np.array([1,2,3,4,5,1,2,1,1,1])

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
a,b = np.unique(x, return_counts=True)
elementx = (a[np.argmax(b)])
indexx = np.where(x == elementx)
print("Max occurrence is of : ",elementx)
print("Indices : ",indexx[0])

# ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

c,d = np.unique(y, return_counts=True)
elementy = (c[np.argmax(d)])
indexy = np.where(y == elementy)
print("Max occurrence is of : ",elementy)
print("Indices : ",indexy[0])

Max occurrence is of :  1
Indices :  [0 5 7 8 9]
Max occurrence is of :  1
Indices :  [0 1 2]


In [3]:
# Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows: a) Access 1st row, 2nd column b) Access 3rd row, 1st column


arr3 = np.array([[10,20,30],[40,50,60],[70,80,90]])

# a) Access 1st row, 2nd column

print("1st Row 2nd Col : ",arr3[0,1])


# b) Access 3rd row, 1st column

print("3rd Row 1st Col : ",arr3[2,0])

1st Row 2nd Col :  20
3rd Row 1st Col :  70


In [4]:
# Q.4 Write program to create an 1-D NumPy array named YourName with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

brahmjeet = np.linspace(10,100,25)
print("Dimension : ",brahmjeet.ndim)
print("Shape : ",brahmjeet.shape)
print("Total Elements : ",brahmjeet.size)
print("Data Type : ",brahmjeet.dtype)
print("Total Bytes : ",brahmjeet.nbytes)
print("Transpose using reshape :",brahmjeet.reshape(25,1))
print("Transpose using T : ",brahmjeet.T)

Dimension :  1
Shape :  (25,)
Total Elements :  25
Data Type :  float64
Total Bytes :  200
Transpose using reshape : [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T :  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [5]:
#  Q5. Create a 2-D Array of three rows and four columns, named ucs420_yourname with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_yourname. Resize the array to two rows and three columns and name it as resized_ ucs420_yourname


ucs420_brahmjeet = np.array([10,20,30,40,50,60,70,80,90,15,20,35])
print("Mean : ",np.mean(ucs420_brahmjeet))
print("Median : ",np.median(ucs420_brahmjeet))
print("Max : ",np.max(ucs420_brahmjeet))
print("Min : ",np.min(ucs420_brahmjeet))
print("Unique : ",np.unique(ucs420_brahmjeet))
reshaped_ucs420_brahmjeet = ucs420_brahmjeet.reshape(4,3)
print("Reshaped : ",reshaped_ucs420_brahmjeet)
resized_ucs420_brahmjeet = np.resize(ucs420_brahmjeet,(2,3))
print("Resized : ",resized_ucs420_brahmjeet)

Mean :  43.333333333333336
Median :  37.5
Max :  90
Min :  10
Unique :  [10 15 20 30 35 40 50 60 70 80 90]
Reshaped :  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized :  [[10 20 30]
 [40 50 60]]
